// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                           18
// Async Callback:                       1
// Total number of exported functions:  21

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    tokenstaking
    (
        init => init
        upgrade => upgrade
        addAdmins => add_admin
        removeAdmins => remove_admin
        isAdmin => is_admin
        getAdmins => admins
        pause => pause
        unpause => unpause
        isPaused => is_paused
        createFarm => create_farm
        modifyStartTs => modify_start_ts
        modifyEndTs => modify_end_ts
        modifyRewards => modify_rewards
        depositRewards => deposit_rewards
        withdrawRewards => withdraw_rewards
        getFarmInfo => get_farm_info
        stake => stake
        unstake => unstake
        claimRewards => claim_rewards_endpoint
        getClaimableRewards => get_claimable_rewards
    )
}

multiversx_sc_wasm_adapter::async_callback! { tokenstaking }
